### PR TITLE
After handling the Call ensure replication of data by calling ReplicateVerbatim

### PR DESCRIPTION
**Pull request by profporridge**
I found these changes necessary to get the module working in a cluster 
#30

### CODE REVIEW

**Comment by brandur** [comment]
Thanks @profporridge!

So I'm just reading the docs for this now and I *think* that there is a little risk in using `RedisModule_ReplicateVerbatim` for redis-cell because executing the same command on a replica will have slightly different results due to the fact that rate limiting implementation uses the current clock time as reference.

Probably the more correct answer for replication would be to add a new throttle command that allows a timestamp to be injected like:

```
CL.THROTTLET <bucket> <max_burst> <rate_size> <rate_duration> <num_tokens> <current_time> <current_time_nano>
```

Then we'd use `RedisModule_Replicate` from the master and inject the time components that it received to all its replicas. That way, the master and all replicas would always be perfectly synchronized.

That said, because of the domain here, it's probably okay to `RedisModule_ReplicateVerbatim` for now and consider the above as a future enhancement. Replicas will not be perfectly synchronized with their master, but for rate limiting it's probably okay for most uses if they're a little bit off.

Thoughts?

**Comment by brandur** [comment]
And by the way, I fixed the build in #32 — yours should start passing if you rebase on `master`.

**Comment by profporridge** [comment]
I like your suggestion, it might even be useful to be able to supply the time (instead of using the current time) in other scenarios. That being said, I don't imagine I would notice a time difference in the rate limiting domain. 

Thanks for fixing the build. I reformatted my changes to please the nightly build gods

**Comment by brandur** [comment]
Okay, I'll put this in and add a few notes about the limitations.

**Comment by brandur** [comment]
Released as 0.2.4.

**Pull request merged**
